repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: flake8
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: fix-encoding-pragma
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        args: [
            '--add-import', 'from __future__ import absolute_import',
            '--add-import', 'from __future__ import unicode_literals',
        ]
-   repo: git://github.com/asottile/pyupgrade
    sha: v1.2.0
    hooks:
    -   id: pyupgrade
-   repo: git://github.com/Yelp/detect-secrets
    sha: 0.9.1
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*tests/.*|\.pre-commit-config\.yaml
